#!/usr/bin/env python3
from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).parent
BASE_JSON = ROOT / "verb_frames.french_200.generated.json"
OUT_JSON = ROOT / "verb_frames.french_300.generated.json"
OUT_JS = ROOT / "verb_frames.french_300.js"
OUT_MD = ROOT / "verb_frames.french_300.md"


MANUAL_EXTRA_ROWS = [
    {
        "verb": "présenter",
        "frame_type": "a_object",
        "question": "La galerie ____ la série ____ public ce soir",
        "answer": "présente au",
        "full_answer": "La galerie présente la série au public ce soir",
        "meaning_en": "The gallery is presenting the series to the public tonight.",
        "category_id": "builtin-art-design",
        "category_name": "Art & Design",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "J'____ ____ galeriste pour décaler la livraison",
        "answer": "écris au",
        "full_answer": "J'écris au galeriste pour décaler la livraison",
        "meaning_en": "I'm writing to the gallery owner to postpone the delivery.",
        "category_id": "builtin-art-design",
        "category_name": "Art & Design",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Nous ____ ____ cette installation depuis l'ouverture",
        "answer": "parlons de",
        "full_answer": "Nous parlons de cette installation depuis l'ouverture",
        "meaning_en": "We're talking about this installation since the opening.",
        "category_id": "builtin-art-design",
        "category_name": "Art & Design",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "raconter",
        "frame_type": "a_object",
        "question": "La médiatrice ____ l'histoire ____ visiteurs dans la grande salle",
        "answer": "raconte aux",
        "full_answer": "La médiatrice raconte l'histoire aux visiteurs dans la grande salle",
        "meaning_en": "The mediator tells the story to the visitors in the large hall.",
        "category_id": "builtin-art-design",
        "category_name": "Art & Design",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "montrer",
        "frame_type": "a_object",
        "question": "Je ____ la maquette ____ collectionneur avant midi",
        "answer": "montre au",
        "full_answer": "Je montre la maquette au collectionneur avant midi",
        "meaning_en": "I'm showing the model to the collector before noon.",
        "category_id": "builtin-art-design",
        "category_name": "Art & Design",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "répondre",
        "frame_type": "a_object",
        "question": "L'équipe ____ ____ critiques après le vernissage",
        "answer": "répond aux",
        "full_answer": "L'équipe répond aux critiques après le vernissage",
        "meaning_en": "The team responds to the critics after the opening.",
        "category_id": "builtin-art-design",
        "category_name": "Art & Design",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "envoyer",
        "frame_type": "a_object",
        "question": "J'____ la copie ____ service des titres avant midi",
        "answer": "envoie au",
        "full_answer": "J'envoie la copie au service des titres avant midi",
        "meaning_en": "I'm sending the copy to the ID office before noon.",
        "category_id": "builtin-bureaucracy-delivery",
        "category_name": "Bureaucracy & Delivery",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "indiquer",
        "frame_type": "a_object",
        "question": "L'agent ____ la file ____ visiteur dès l'entrée",
        "answer": "indique au",
        "full_answer": "L'agent indique la file au visiteur dès l'entrée",
        "meaning_en": "The clerk points out the line to the visitor right at the entrance.",
        "category_id": "builtin-bureaucracy-delivery",
        "category_name": "Bureaucracy & Delivery",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "répondre",
        "frame_type": "a_object",
        "question": "Nous ____ ____ demandeur avant la fermeture",
        "answer": "répondons au",
        "full_answer": "Nous répondons au demandeur avant la fermeture",
        "meaning_en": "We're replying to the applicant before closing.",
        "category_id": "builtin-bureaucracy-delivery",
        "category_name": "Bureaucracy & Delivery",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "joindre",
        "frame_type": "a_object",
        "question": "Je ____ le justificatif ____ la réclamation en ligne",
        "answer": "joins à",
        "full_answer": "Je joins le justificatif à la réclamation en ligne",
        "meaning_en": "I'm attaching the supporting document to the online complaint.",
        "category_id": "builtin-bureaucracy-delivery",
        "category_name": "Bureaucracy & Delivery",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "passer",
        "frame_type": "a_object",
        "question": "Le bureau ____ ____ dossier suivant à onze heures",
        "answer": "passe au",
        "full_answer": "Le bureau passe au dossier suivant à onze heures",
        "meaning_en": "The office moves on to the next file at eleven.",
        "category_id": "builtin-bureaucracy-delivery",
        "category_name": "Bureaucracy & Delivery",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "venir",
        "frame_type": "a_object",
        "question": "Vous ____ ____ bureau B avec le reçu provisoire",
        "answer": "venez au",
        "full_answer": "Vous venez au bureau B avec le reçu provisoire",
        "meaning_en": "You come to desk B with the temporary receipt.",
        "category_id": "builtin-bureaucracy-delivery",
        "category_name": "Bureaucracy & Delivery",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "raconter",
        "frame_type": "a_object",
        "question": "La critique ____ la scène ____ producteur à la sortie",
        "answer": "raconte au",
        "full_answer": "La critique raconte la scène au producteur à la sortie",
        "meaning_en": "The critic recounts the scene to the producer on the way out.",
        "category_id": "builtin-cinema-series",
        "category_name": "Cinema & Series",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "tourner",
        "frame_type": "a_object",
        "question": "Le ton ____ ____ la farce après la panne",
        "answer": "tourne à",
        "full_answer": "Le ton tourne à la farce après la panne",
        "meaning_en": "The tone turns into farce after the breakdown.",
        "category_id": "builtin-cinema-series",
        "category_name": "Cinema & Series",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "La journaliste ____ ____ réalisateur après l'avant-première",
        "answer": "écrit au",
        "full_answer": "La journaliste écrit au réalisateur après l'avant-première",
        "meaning_en": "The journalist writes to the director after the premiere.",
        "category_id": "builtin-cinema-series",
        "category_name": "Cinema & Series",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Ils ____ ____ casting en descendant l'avenue",
        "answer": "parlent du",
        "full_answer": "Ils parlent du casting en descendant l'avenue",
        "meaning_en": "They're talking about the casting while walking down the avenue.",
        "category_id": "builtin-cinema-series",
        "category_name": "Cinema & Series",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "présenter",
        "frame_type": "a_object",
        "question": "La modératrice ____ l'équipe ____ public avant la projection",
        "answer": "présente au",
        "full_answer": "La modératrice présente l'équipe au public avant la projection",
        "meaning_en": "The host introduces the team to the audience before the screening.",
        "category_id": "builtin-cinema-series",
        "category_name": "Cinema & Series",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "montrer",
        "frame_type": "a_object",
        "question": "Le journaliste ____ la bande-annonce ____ monteur pendant la pause",
        "answer": "montre au",
        "full_answer": "Le journaliste montre la bande-annonce au monteur pendant la pause",
        "meaning_en": "The journalist shows the trailer to the editor during the break.",
        "category_id": "builtin-cinema-series",
        "category_name": "Cinema & Series",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "servir",
        "frame_type": "a_object",
        "question": "Je ____ la salade ____ voisins dans le jardin",
        "answer": "sers aux",
        "full_answer": "Je sers la salade aux voisins dans le jardin",
        "meaning_en": "I'm serving the salad to the neighbors in the garden.",
        "category_id": "builtin-cooking-food",
        "category_name": "Cooking & Food",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "mélanger",
        "frame_type": "a_object",
        "question": "Tu ____ le miel ____ la moutarde pour la sauce",
        "answer": "mélanges à",
        "full_answer": "Tu mélanges le miel à la moutarde pour la sauce",
        "meaning_en": "You're mixing the honey into the mustard for the sauce.",
        "category_id": "builtin-cooking-food",
        "category_name": "Cooking & Food",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "goûter",
        "frame_type": "a_object",
        "question": "Le chef ____ ____ la soupe avant le service",
        "answer": "goûte à",
        "full_answer": "Le chef goûte à la soupe avant le service",
        "meaning_en": "The chef tastes the soup before service.",
        "category_id": "builtin-cooking-food",
        "category_name": "Cooking & Food",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Nous ____ ____ dessert pendant que le four chauffe",
        "answer": "parlons du",
        "full_answer": "Nous parlons du dessert pendant que le four chauffe",
        "meaning_en": "We're talking about dessert while the oven heats up.",
        "category_id": "builtin-cooking-food",
        "category_name": "Cooking & Food",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "verser",
        "frame_type": "a_object",
        "question": "Elle ____ le thé ____ invités dans de petites tasses",
        "answer": "verse aux",
        "full_answer": "Elle verse le thé aux invités dans de petites tasses",
        "meaning_en": "She pours tea for the guests into small cups.",
        "category_id": "builtin-cooking-food",
        "category_name": "Cooking & Food",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "servir",
        "frame_type": "de_object",
        "question": "Ce grand plateau ____ ____ table d'appoint pendant le buffet",
        "answer": "sert de",
        "full_answer": "Ce grand plateau sert de table d'appoint pendant le buffet",
        "meaning_en": "This large tray serves as a side table during the buffet.",
        "category_id": "builtin-cooking-food",
        "category_name": "Cooking & Food",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "coller",
        "frame_type": "a_object",
        "question": "Je ____ la doublure ____ carnet avant la reliure",
        "answer": "colle au",
        "full_answer": "Je colle la doublure au carnet avant la reliure",
        "meaning_en": "I'm gluing the lining onto the notebook before binding it.",
        "category_id": "builtin-crafts-making",
        "category_name": "Crafts & Making",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "coudre",
        "frame_type": "a_object",
        "question": "Tu ____ le galon ____ coussin en velours",
        "answer": "couds au",
        "full_answer": "Tu couds le galon au coussin en velours",
        "meaning_en": "You're sewing the trim onto the velvet cushion.",
        "category_id": "builtin-crafts-making",
        "category_name": "Crafts & Making",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "ajuster",
        "frame_type": "a_object",
        "question": "J'____ la boucle ____ bracelet avant la photo",
        "answer": "ajuste au",
        "full_answer": "J'ajuste la boucle au bracelet avant la photo",
        "meaning_en": "I'm fitting the buckle to the bracelet before the photo.",
        "category_id": "builtin-crafts-making",
        "category_name": "Crafts & Making",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "servir",
        "frame_type": "de_object",
        "question": "Cette vieille caisse ____ ____ boîte à outils dans l'atelier",
        "answer": "sert de",
        "full_answer": "Cette vieille caisse sert de boîte à outils dans l'atelier",
        "meaning_en": "This old crate serves as a toolbox in the workshop.",
        "category_id": "builtin-crafts-making",
        "category_name": "Crafts & Making",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "On ____ ____ fournisseur pour remplacer la sangle",
        "answer": "écrit au",
        "full_answer": "On écrit au fournisseur pour remplacer la sangle",
        "meaning_en": "We're writing to the supplier to replace the strap.",
        "category_id": "builtin-crafts-making",
        "category_name": "Crafts & Making",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "présenter",
        "frame_type": "a_object",
        "question": "La créatrice ____ ses broches ____ clientes du marché",
        "answer": "présente aux",
        "full_answer": "La créatrice présente ses broches aux clientes du marché",
        "meaning_en": "The designer presents her brooches to the market customers.",
        "category_id": "builtin-crafts-making",
        "category_name": "Crafts & Making",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "expliquer",
        "frame_type": "a_object",
        "question": "La prof ____ l'exercice ____ retardataires après la sonnerie",
        "answer": "explique aux",
        "full_answer": "La prof explique l'exercice aux retardataires après la sonnerie",
        "meaning_en": "The teacher explains the exercise to the latecomers after the bell.",
        "category_id": "builtin-education-learning",
        "category_name": "Education & Learning",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "J'____ ____ proviseur pour demander une salle",
        "answer": "écris au",
        "full_answer": "J'écris au proviseur pour demander une salle",
        "meaning_en": "I'm writing to the principal to request a room.",
        "category_id": "builtin-education-learning",
        "category_name": "Education & Learning",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "apprendre",
        "frame_type": "de_object",
        "question": "On ____ ____ chaque brouillon avant l'oral",
        "answer": "apprend de",
        "full_answer": "On apprend de chaque brouillon avant l'oral",
        "meaning_en": "You learn from each draft before the oral exam.",
        "category_id": "builtin-education-learning",
        "category_name": "Education & Learning",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "présenter",
        "frame_type": "a_object",
        "question": "L'étudiant ____ sa carte ____ surveillant à l'entrée",
        "answer": "présente au",
        "full_answer": "L'étudiant présente sa carte au surveillant à l'entrée",
        "meaning_en": "The student shows their card to the supervisor at the entrance.",
        "category_id": "builtin-education-learning",
        "category_name": "Education & Learning",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Nous ____ ____ contrôle pendant la pause",
        "answer": "parlons du",
        "full_answer": "Nous parlons du contrôle pendant la pause",
        "meaning_en": "We're talking about the test during the break.",
        "category_id": "builtin-education-learning",
        "category_name": "Education & Learning",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "répondre",
        "frame_type": "a_object",
        "question": "Le tuteur ____ ____ questions avant le TD",
        "answer": "répond aux",
        "full_answer": "Le tuteur répond aux questions avant le TD",
        "meaning_en": "The tutor answers the questions before the tutorial.",
        "category_id": "builtin-education-learning",
        "category_name": "Education & Learning",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "raconter",
        "frame_type": "a_object",
        "question": "Le guide ____ la bataille ____ visiteurs sous l'arche",
        "answer": "raconte aux",
        "full_answer": "Le guide raconte la bataille aux visiteurs sous l'arche",
        "meaning_en": "The guide tells the visitors about the battle under the arch.",
        "category_id": "builtin-history-culture",
        "category_name": "History & Culture",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "L'historienne ____ ____ musée pour consulter les dossiers",
        "answer": "écrit au",
        "full_answer": "L'historienne écrit au musée pour consulter les dossiers",
        "meaning_en": "The historian writes to the museum to consult the files.",
        "category_id": "builtin-history-culture",
        "category_name": "History & Culture",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Ils ____ ____ chantier devant la chapelle",
        "answer": "parlent du",
        "full_answer": "Ils parlent du chantier devant la chapelle",
        "meaning_en": "They're talking about the worksite in front of the chapel.",
        "category_id": "builtin-history-culture",
        "category_name": "History & Culture",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "présenter",
        "frame_type": "a_object",
        "question": "Le centre ____ ses archives ____ public cet automne",
        "answer": "présente au",
        "full_answer": "Le centre présente ses archives au public cet automne",
        "meaning_en": "The center presents its archives to the public this autumn.",
        "category_id": "builtin-history-culture",
        "category_name": "History & Culture",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "traduire",
        "frame_type": "de_object",
        "question": "Je ____ ____ grec une inscription trouvée près du port",
        "answer": "traduis du",
        "full_answer": "Je traduis du grec une inscription trouvée près du port",
        "meaning_en": "I'm translating an inscription from Greek that was found near the harbor.",
        "category_id": "builtin-history-culture",
        "category_name": "History & Culture",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "répondre",
        "frame_type": "a_object",
        "question": "La médiatrice ____ ____ scolaires après la visite",
        "answer": "répond aux",
        "full_answer": "La médiatrice répond aux scolaires après la visite",
        "meaning_en": "The mediator answers the schoolchildren after the visit.",
        "category_id": "builtin-history-culture",
        "category_name": "History & Culture",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "jouer",
        "frame_type": "de_object",
        "question": "Je ____ ____ piano sur l'intro ce soir",
        "answer": "joue du",
        "full_answer": "Je joue du piano sur l'intro ce soir",
        "meaning_en": "I'm playing piano on the intro tonight.",
        "category_id": "builtin-music",
        "category_name": "Music",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "assurer",
        "frame_type": "a_object",
        "question": "Le régisseur ____ ____ batteur un retour plus net",
        "answer": "assure au",
        "full_answer": "Le régisseur assure au batteur un retour plus net",
        "meaning_en": "The stage manager gives the drummer a clearer monitor feed.",
        "category_id": "builtin-music",
        "category_name": "Music",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Nous ____ ____ rappel en rangeant les câbles",
        "answer": "parlons du",
        "full_answer": "Nous parlons du rappel en rangeant les câbles",
        "meaning_en": "We're talking about the encore while coiling the cables.",
        "category_id": "builtin-music",
        "category_name": "Music",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "accorder",
        "frame_type": "a_object",
        "question": "J'____ la guitare ____ l'oreille derrière le rideau",
        "answer": "accorde à",
        "full_answer": "J'accorde la guitare à l'oreille derrière le rideau",
        "meaning_en": "I'm tuning the guitar by ear behind the curtain.",
        "category_id": "builtin-music",
        "category_name": "Music",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "inviter",
        "frame_type": "a_object",
        "question": "On ____ le public ____ chanter sur le dernier refrain",
        "answer": "invite à",
        "full_answer": "On invite le public à chanter sur le dernier refrain",
        "meaning_en": "We're inviting the audience to sing on the last chorus.",
        "category_id": "builtin-music",
        "category_name": "Music",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "répondre",
        "frame_type": "a_object",
        "question": "La chanteuse ____ ____ fans après la balance",
        "answer": "répond aux",
        "full_answer": "La chanteuse répond aux fans après la balance",
        "meaning_en": "The singer replies to the fans after soundcheck.",
        "category_id": "builtin-music",
        "category_name": "Music",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "trinquer",
        "frame_type": "a_object",
        "question": "Je ____ ____ ton retour avant minuit",
        "answer": "trinque à",
        "full_answer": "Je trinque à ton retour avant minuit",
        "meaning_en": "I'm toasting your return before midnight.",
        "category_id": "builtin-nightlife-partying",
        "category_name": "Nightlife & Partying",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "sortir",
        "frame_type": "a_object",
        "question": "On ____ ____ club vers une heure du matin",
        "answer": "sort au",
        "full_answer": "On sort au club vers une heure du matin",
        "meaning_en": "We're going out to the club around one in the morning.",
        "category_id": "builtin-nightlife-partying",
        "category_name": "Nightlife & Partying",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "inviter",
        "frame_type": "a_object",
        "question": "J'____ les voisins ____ notre after sur la péniche",
        "answer": "invite à",
        "full_answer": "J'invite les voisins à notre after sur la péniche",
        "meaning_en": "I'm inviting the neighbors to our after-party on the barge.",
        "category_id": "builtin-nightlife-partying",
        "category_name": "Nightlife & Partying",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Nous ____ ____ set en attendant le taxi",
        "answer": "parlons du",
        "full_answer": "Nous parlons du set en attendant le taxi",
        "meaning_en": "We're talking about the set while waiting for the taxi.",
        "category_id": "builtin-nightlife-partying",
        "category_name": "Nightlife & Partying",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "répondre",
        "frame_type": "a_object",
        "question": "Le DJ ____ ____ demandes entre deux morceaux",
        "answer": "répond aux",
        "full_answer": "Le DJ répond aux demandes entre deux morceaux",
        "meaning_en": "The DJ responds to requests between two tracks.",
        "category_id": "builtin-nightlife-partying",
        "category_name": "Nightlife & Partying",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "Elle ____ ____ videur pour récupérer son écharpe",
        "answer": "écrit au",
        "full_answer": "Elle écrit au videur pour récupérer son écharpe",
        "meaning_en": "She writes to the bouncer to get her scarf back.",
        "category_id": "builtin-nightlife-partying",
        "category_name": "Nightlife & Partying",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "présenter",
        "frame_type": "a_object",
        "question": "Je ____ le projet ____ directeurs avant onze heures",
        "answer": "présente aux",
        "full_answer": "Je présente le projet aux directeurs avant onze heures",
        "meaning_en": "I'm presenting the project to the directors before eleven.",
        "category_id": "builtin-office-admin",
        "category_name": "Office & Admin",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "assurer",
        "frame_type": "a_object",
        "question": "Le manager ____ ____ client un compte-rendu vendredi",
        "answer": "assure au",
        "full_answer": "Le manager assure au client un compte-rendu vendredi",
        "meaning_en": "The manager guarantees the client a written update on Friday.",
        "category_id": "builtin-office-admin",
        "category_name": "Office & Admin",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "transférer",
        "frame_type": "a_object",
        "question": "Nous ____ le dossier ____ service paie avant midi",
        "answer": "transférons au",
        "full_answer": "Nous transférons le dossier au service paie avant midi",
        "meaning_en": "We're transferring the file to payroll before noon.",
        "category_id": "builtin-office-admin",
        "category_name": "Office & Admin",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "répondre",
        "frame_type": "de_object",
        "question": "Il ____ ____ dossier devant l'auditeur",
        "answer": "répond du",
        "full_answer": "Il répond du dossier devant l'auditeur",
        "meaning_en": "He is answerable for the file before the auditor.",
        "category_id": "builtin-office-admin",
        "category_name": "Office & Admin",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "J'____ ____ support pour débloquer le compte",
        "answer": "écris au",
        "full_answer": "J'écris au support pour débloquer le compte",
        "meaning_en": "I'm writing to support to unlock the account.",
        "category_id": "builtin-office-admin",
        "category_name": "Office & Admin",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "On ____ ____ planning pendant le point du matin",
        "answer": "parle du",
        "full_answer": "On parle du planning pendant le point du matin",
        "meaning_en": "We're talking about the schedule during the morning check-in.",
        "category_id": "builtin-office-admin",
        "category_name": "Office & Admin",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "grimper",
        "frame_type": "a_object",
        "question": "Nous ____ ____ refuge avant les nuages",
        "answer": "grimpons au",
        "full_answer": "Nous grimpons au refuge avant les nuages",
        "meaning_en": "We're climbing up to the refuge before the clouds roll in.",
        "category_id": "builtin-outdoors-nature",
        "category_name": "Outdoors & Nature",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "grimper",
        "frame_type": "a_object",
        "question": "Le chat ____ ____ rocher pour voir la rivière",
        "answer": "grimpe au",
        "full_answer": "Le chat grimpe au rocher pour voir la rivière",
        "meaning_en": "The cat climbs up the rock to see the river.",
        "category_id": "builtin-outdoors-nature",
        "category_name": "Outdoors & Nature",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "arriver",
        "frame_type": "a_object",
        "question": "On ____ ____ col avant la chaleur",
        "answer": "arrive au",
        "full_answer": "On arrive au col avant la chaleur",
        "meaning_en": "We arrive at the pass before the heat builds up.",
        "category_id": "builtin-outdoors-nature",
        "category_name": "Outdoors & Nature",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Nous ____ ____ sentier près de la source",
        "answer": "parlons du",
        "full_answer": "Nous parlons du sentier près de la source",
        "meaning_en": "We're talking about the trail near the spring.",
        "category_id": "builtin-outdoors-nature",
        "category_name": "Outdoors & Nature",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "venir",
        "frame_type": "de_object",
        "question": "Je ____ ____ vallon avec les gourdes pleines",
        "answer": "viens du",
        "full_answer": "Je viens du vallon avec les gourdes pleines",
        "meaning_en": "I'm coming from the valley with the bottles full.",
        "category_id": "builtin-outdoors-nature",
        "category_name": "Outdoors & Nature",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "passer",
        "frame_type": "a_object",
        "question": "Le groupe ____ ____ belvédère avant de redescendre",
        "answer": "passe au",
        "full_answer": "Le groupe passe au belvédère avant de redescendre",
        "meaning_en": "The group stops by the viewpoint before heading back down.",
        "category_id": "builtin-outdoors-nature",
        "category_name": "Outdoors & Nature",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "accuser",
        "frame_type": "de_object",
        "question": "L'opposition ____ le maire ____avoir enterré le rapport",
        "answer": "accuse d'",
        "full_answer": "L'opposition accuse le maire d'avoir enterré le rapport",
        "meaning_en": "The opposition accuses the mayor of having buried the report.",
        "category_id": "builtin-politics-current-events",
        "category_name": "Politics & Current Events",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "débattre",
        "frame_type": "de_object",
        "question": "Les députés ____ ____ budget jusque tard",
        "answer": "débattent du",
        "full_answer": "Les députés débattent du budget jusque tard",
        "meaning_en": "The MPs debate the budget until late.",
        "category_id": "builtin-politics-current-events",
        "category_name": "Politics & Current Events",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "imposer",
        "frame_type": "a_object",
        "question": "Le ministre ____ une règle ____ préfets dès lundi",
        "answer": "impose aux",
        "full_answer": "Le ministre impose une règle aux préfets dès lundi",
        "meaning_en": "The minister imposes a rule on the prefects starting Monday.",
        "category_id": "builtin-politics-current-events",
        "category_name": "Politics & Current Events",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "promettre",
        "frame_type": "a_object",
        "question": "La candidate ____ une aide ____ aides-soignantes",
        "answer": "promet aux",
        "full_answer": "La candidate promet une aide aux aides-soignantes",
        "meaning_en": "The candidate promises aid to care assistants.",
        "category_id": "builtin-politics-current-events",
        "category_name": "Politics & Current Events",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "répondre",
        "frame_type": "a_object",
        "question": "Le porte-parole ____ ____ journalistes à la sortie",
        "answer": "répond aux",
        "full_answer": "Le porte-parole répond aux journalistes à la sortie",
        "meaning_en": "The spokesperson responds to the journalists on the way out.",
        "category_id": "builtin-politics-current-events",
        "category_name": "Politics & Current Events",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "mentir",
        "frame_type": "a_object",
        "question": "Il ____ ____ Claire depuis des semaines",
        "answer": "ment à",
        "full_answer": "Il ment à Claire depuis des semaines",
        "meaning_en": "He's been lying to Claire for weeks.",
        "category_id": "builtin-relationship-drama",
        "category_name": "Relationship Drama",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Nous ____ ____ conflit dans la cuisine",
        "answer": "parlons du",
        "full_answer": "Nous parlons du conflit dans la cuisine",
        "meaning_en": "We're talking about the conflict in the kitchen.",
        "category_id": "builtin-relationship-drama",
        "category_name": "Relationship Drama",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "sortir",
        "frame_type": "de_object",
        "question": "Elle ____ ____ piège avant l'été",
        "answer": "sort du",
        "full_answer": "Elle sort du piège avant l'été",
        "meaning_en": "She gets out of the trap before summer.",
        "category_id": "builtin-relationship-drama",
        "category_name": "Relationship Drama",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "pardonner",
        "frame_type": "a_object",
        "question": "Je ____ enfin ____ Nina après son appel",
        "answer": "pardonne à",
        "full_answer": "Je pardonne enfin à Nina après son appel",
        "meaning_en": "I finally forgive Nina after her call.",
        "category_id": "builtin-relationship-drama",
        "category_name": "Relationship Drama",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "reprocher",
        "frame_type": "a_object",
        "question": "Elle ____ ____ Paul son silence au dessert",
        "answer": "reproche à",
        "full_answer": "Elle reproche à Paul son silence au dessert",
        "meaning_en": "She reproaches Paul for his silence over dessert.",
        "category_id": "builtin-relationship-drama",
        "category_name": "Relationship Drama",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "J'____ ____ Léa pour rendre les clés",
        "answer": "écris à",
        "full_answer": "J'écris à Léa pour rendre les clés",
        "meaning_en": "I'm writing to Léa to return the keys.",
        "category_id": "builtin-relationship-drama",
        "category_name": "Relationship Drama",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "jouer",
        "frame_type": "a_object",
        "question": "On ____ ____ handball près du canal le mercredi",
        "answer": "joue au",
        "full_answer": "On joue au handball près du canal le mercredi",
        "meaning_en": "We're playing handball by the canal on Wednesdays.",
        "category_id": "builtin-sports-fitness",
        "category_name": "Sports & Fitness",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "marquer",
        "frame_type": "de_object",
        "question": "L'ailier ____ ____ ____ la tête sur le corner entrant",
        "answer": "marque de la",
        "full_answer": "L'ailier marque de la tête sur le corner entrant",
        "meaning_en": "The winger scores with a header from the inswinging corner.",
        "category_id": "builtin-sports-fitness",
        "category_name": "Sports & Fitness",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "a_object",
        "question": "Le coach ____ ____ remplaçants juste avant le coup d'envoi",
        "answer": "parle aux",
        "full_answer": "Le coach parle aux remplaçants juste avant le coup d'envoi",
        "meaning_en": "The coach talks to the substitutes right before kickoff.",
        "category_id": "builtin-sports-fitness",
        "category_name": "Sports & Fitness",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "changer",
        "frame_type": "de_object",
        "question": "L'entraîneur ____ ____ gardien avant les tirs au but",
        "answer": "change de",
        "full_answer": "L'entraîneur change de gardien avant les tirs au but",
        "meaning_en": "The coach changes goalkeeper before the penalty shootout.",
        "category_id": "builtin-sports-fitness",
        "category_name": "Sports & Fitness",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "frapper",
        "frame_type": "de_object",
        "question": "Je ____ ____ droit quand le centre revient au premier poteau",
        "answer": "frappe du",
        "full_answer": "Je frappe du droit quand le centre revient au premier poteau",
        "meaning_en": "I strike it with my right foot when the cross comes back to the near post.",
        "category_id": "builtin-sports-fitness",
        "category_name": "Sports & Fitness",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "répondre",
        "frame_type": "a_object",
        "question": "Le capitaine ____ ____ supporters après la rencontre",
        "answer": "répond aux",
        "full_answer": "Le capitaine répond aux supporters après la rencontre",
        "meaning_en": "The captain responds to the supporters after the match.",
        "category_id": "builtin-sports-fitness",
        "category_name": "Sports & Fitness",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "acheter",
        "frame_type": "a_object",
        "question": "J'____ un croissant ____ kiosque du quai avant le TER",
        "answer": "achète au",
        "full_answer": "J'achète un croissant au kiosque du quai avant le TER",
        "meaning_en": "I'm buying a croissant at the platform kiosk before the regional train.",
        "category_id": "builtin-super-everyday",
        "category_name": "Super Everyday",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "demander",
        "frame_type": "a_object",
        "question": "Je ____ ____ voisin de garder mon sac deux minutes",
        "answer": "demande au",
        "full_answer": "Je demande au voisin de garder mon sac deux minutes",
        "meaning_en": "I ask the neighbor to watch my bag for two minutes.",
        "category_id": "builtin-super-everyday",
        "category_name": "Super Everyday",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Nous ____ ____ départ pendant le petit-déjeuner",
        "answer": "parlons du",
        "full_answer": "Nous parlons du départ pendant le petit-déjeuner",
        "meaning_en": "We're talking about the departure over breakfast.",
        "category_id": "builtin-super-everyday",
        "category_name": "Super Everyday",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "envoyer",
        "frame_type": "a_object",
        "question": "J'____ la photo ____ groupe familial ce soir",
        "answer": "envoie au",
        "full_answer": "J'envoie la photo au groupe familial ce soir",
        "meaning_en": "I'm sending the photo to the family group tonight.",
        "category_id": "builtin-super-everyday",
        "category_name": "Super Everyday",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "venir",
        "frame_type": "de_object",
        "question": "Je ____ ____ marché avec deux sacs lourds",
        "answer": "viens du",
        "full_answer": "Je viens du marché avec deux sacs lourds",
        "meaning_en": "I'm coming back from the market with two heavy bags.",
        "category_id": "builtin-super-everyday",
        "category_name": "Super Everyday",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "partir",
        "frame_type": "de_object",
        "question": "Le car ____ ____ terminal avant l'aube",
        "answer": "part du",
        "full_answer": "Le car part du terminal avant l'aube",
        "meaning_en": "The coach leaves from the terminal before dawn.",
        "category_id": "builtin-travel-tourism",
        "category_name": "Travel & Tourism",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "arriver",
        "frame_type": "a_object",
        "question": "Nous ____ ____ port avant les autres groupes",
        "answer": "arrivons au",
        "full_answer": "Nous arrivons au port avant les autres groupes",
        "meaning_en": "We arrive at the harbor before the other groups.",
        "category_id": "builtin-travel-tourism",
        "category_name": "Travel & Tourism",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "louer",
        "frame_type": "a_object",
        "question": "On ____ la chambre ____ randonneurs pendant le festival",
        "answer": "loue aux",
        "full_answer": "On loue la chambre aux randonneurs pendant le festival",
        "meaning_en": "We're renting the room to hikers during the festival.",
        "category_id": "builtin-travel-tourism",
        "category_name": "Travel & Tourism",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Je ____ ____ trajet avec le chauffeur du minibus",
        "answer": "parle du",
        "full_answer": "Je parle du trajet avec le chauffeur du minibus",
        "meaning_en": "I'm talking about the route with the minibus driver.",
        "category_id": "builtin-travel-tourism",
        "category_name": "Travel & Tourism",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "J'____ ____ camping pour confirmer l'heure d'arrivée",
        "answer": "écris au",
        "full_answer": "J'écris au camping pour confirmer l'heure d'arrivée",
        "meaning_en": "I'm writing to the campsite to confirm the arrival time.",
        "category_id": "builtin-travel-tourism",
        "category_name": "Travel & Tourism",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "payer",
        "frame_type": "a_object",
        "question": "Je ____ un supplément ____ réceptionniste pour garder la chambre",
        "answer": "paie au",
        "full_answer": "Je paie un supplément au réceptionniste pour garder la chambre",
        "meaning_en": "I pay the receptionist a surcharge to keep the room.",
        "category_id": "builtin-travel-tourism",
        "category_name": "Travel & Tourism",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "ajuster",
        "frame_type": "a_object",
        "question": "J'____ le gabarit ____ panneau étroit pour la découpe",
        "answer": "ajuste au",
        "full_answer": "J'ajuste le gabarit au panneau étroit pour la découpe",
        "meaning_en": "I'm adjusting the jig to the narrow panel for the cut.",
        "category_id": "builtin-woodworking",
        "category_name": "Woodworking",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "coller",
        "frame_type": "a_object",
        "question": "Je ____ la traverse ____ panneau avant le serrage",
        "answer": "colle au",
        "full_answer": "Je colle la traverse au panneau avant le serrage",
        "meaning_en": "I'm gluing the rail onto the panel before clamping.",
        "category_id": "builtin-woodworking",
        "category_name": "Woodworking",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "servir",
        "frame_type": "de_object",
        "question": "Ce vieux guide ____ ____ référence pour la coupe d'onglet",
        "answer": "sert de",
        "full_answer": "Ce vieux guide sert de référence pour la coupe d'onglet",
        "meaning_en": "This old guide serves as a reference for the miter cut.",
        "category_id": "builtin-woodworking",
        "category_name": "Woodworking",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Nous ____ ____ veinage avant de vernir la porte",
        "answer": "parlons du",
        "full_answer": "Nous parlons du veinage avant de vernir la porte",
        "meaning_en": "We're talking about the grain pattern before varnishing the door.",
        "category_id": "builtin-woodworking",
        "category_name": "Woodworking",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "J'____ ____ fournisseur pour remplacer les charnières",
        "answer": "écris au",
        "full_answer": "J'écris au fournisseur pour remplacer les charnières",
        "meaning_en": "I'm writing to the supplier to replace the hinges.",
        "category_id": "builtin-woodworking",
        "category_name": "Woodworking",
        "note": "manual_hundred_expansion",
    },
    {
        "verb": "passer",
        "frame_type": "a_object",
        "question": "On ____ ____ ponçage après le collage",
        "answer": "passe au",
        "full_answer": "On passe au ponçage après le collage",
        "meaning_en": "We move on to sanding after the gluing stage.",
        "category_id": "builtin-woodworking",
        "category_name": "Woodworking",
        "note": "manual_hundred_expansion",
    },
]


def load_rows(path: Path) -> list[dict]:
    return json.loads(path.read_text(encoding="utf-8"))


def rebuild_ids(rows: list[dict]) -> list[dict]:
    family_counter: dict[tuple[str, str], int] = defaultdict(int)
    rebuilt = []
    for row in rows:
        item = dict(row)
        key = (item["verb"], item["frame_type"])
        family_counter[key] += 1
        item["frame_id"] = f"{item['verb']}_{item['frame_type']}_{family_counter[key]:02d}"
        rebuilt.append(item)
    return rebuilt


def write_outputs(rows: list[dict]) -> None:
    OUT_JSON.write_text(json.dumps(rows, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    OUT_JS.write_text("window.verbFrames = " + json.dumps(rows, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")

    by_category = Counter(row.get("category_name") or "" for row in rows)
    by_source = Counter(row.get("source") or "" for row in rows)
    lines = [
        "# French 300 Deck",
        "",
        f"- Total frame cards: {len(rows)}",
        "",
        "## By Source",
        "",
    ]
    for source, count in sorted(by_source.items()):
        lines.append(f"- {source}: {count}")
    lines.extend([
        "",
        "## By Category",
        "",
    ])
    for category_name, count in sorted(by_category.items()):
        lines.append(f"- {category_name}: {count}")
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    base_rows = load_rows(BASE_JSON)
    extra_rows = []
    for row in MANUAL_EXTRA_ROWS:
        item = dict(row)
        item["type"] = "frame"
        item["tense"] = "present"
        item["source"] = "manual_hundred_expansion"
        extra_rows.append(item)
    merged = rebuild_ids(base_rows + extra_rows)
    write_outputs(merged)
    print(f"Wrote {len(merged)} frame cards to {OUT_JSON}")


if __name__ == "__main__":
    main()
