#!/usr/bin/env python3
from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).parent
BASE_JSON = ROOT / "verb_frames.french_150.generated.json"
OUT_JSON = ROOT / "verb_frames.french_200.generated.json"
OUT_JS = ROOT / "verb_frames.french_200.js"
OUT_MD = ROOT / "verb_frames.french_200.md"


MANUAL_EXTRA_ROWS = [
    {
        "verb": "présenter",
        "frame_type": "a_object",
        "question": "La galerie ____ ses maquettes ____ public ce week-end",
        "answer": "présente au",
        "full_answer": "La galerie présente ses maquettes au public ce week-end",
        "meaning_en": "The gallery is presenting its models to the public this weekend.",
        "category_id": "builtin-art-design",
        "category_name": "Art & Design",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "expliquer",
        "frame_type": "a_object",
        "question": "Le commissaire ____ le parcours ____ visiteurs dès l'entrée",
        "answer": "explique aux",
        "full_answer": "Le commissaire explique le parcours aux visiteurs dès l'entrée",
        "meaning_en": "The curator explains the route to the visitors right at the entrance.",
        "category_id": "builtin-art-design",
        "category_name": "Art & Design",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "J'____ ____ galeriste pour confirmer le transport",
        "answer": "écris au",
        "full_answer": "J'écris au galeriste pour confirmer le transport",
        "meaning_en": "I'm writing to the gallery owner to confirm the transport.",
        "category_id": "builtin-art-design",
        "category_name": "Art & Design",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "appeler",
        "frame_type": "a_object",
        "question": "J'____ ____ service des cartes dès huit heures",
        "answer": "appelle au",
        "full_answer": "J'appelle au service des cartes dès huit heures",
        "meaning_en": "I'm calling the card office at eight sharp.",
        "category_id": "builtin-bureaucracy-delivery",
        "category_name": "Bureaucracy & Delivery",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "passer",
        "frame_type": "a_object",
        "question": "L'agent ____ ____ dossier suivant sans lever les yeux",
        "answer": "passe au",
        "full_answer": "L'agent passe au dossier suivant sans lever les yeux",
        "meaning_en": "The clerk moves on to the next file without looking up.",
        "category_id": "builtin-bureaucracy-delivery",
        "category_name": "Bureaucracy & Delivery",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "joindre",
        "frame_type": "a_object",
        "question": "Nous ____ la facture ____ la demande en ligne",
        "answer": "joignons à",
        "full_answer": "Nous joignons la facture à la demande en ligne",
        "meaning_en": "We're attaching the invoice to the online request.",
        "category_id": "builtin-bureaucracy-delivery",
        "category_name": "Bureaucracy & Delivery",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "répondre",
        "frame_type": "a_object",
        "question": "Le bureau ____ ____ habitants avant la fermeture",
        "answer": "répond aux",
        "full_answer": "Le bureau répond aux habitants avant la fermeture",
        "meaning_en": "The office replies to the residents before closing.",
        "category_id": "builtin-bureaucracy-delivery",
        "category_name": "Bureaucracy & Delivery",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "raconter",
        "frame_type": "a_object",
        "question": "Le critique ____ la fin ____ réalisateur après la séance",
        "answer": "raconte au",
        "full_answer": "Le critique raconte la fin au réalisateur après la séance",
        "meaning_en": "The critic recounts the ending to the director after the screening.",
        "category_id": "builtin-cinema-series",
        "category_name": "Cinema & Series",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "tourner",
        "frame_type": "a_object",
        "question": "Le drame ____ ____ la comédie au dernier épisode",
        "answer": "tourne à",
        "full_answer": "Le drame tourne à la comédie au dernier épisode",
        "meaning_en": "The drama turns into comedy in the last episode.",
        "category_id": "builtin-cinema-series",
        "category_name": "Cinema & Series",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "La journaliste ____ ____ producteur au sujet du tournage",
        "answer": "écrit au",
        "full_answer": "La journaliste écrit au producteur au sujet du tournage",
        "meaning_en": "The journalist is writing to the producer about the shoot.",
        "category_id": "builtin-cinema-series",
        "category_name": "Cinema & Series",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "servir",
        "frame_type": "a_object",
        "question": "Je ____ le dessert ____ voisins sur la terrasse",
        "answer": "sers aux",
        "full_answer": "Je sers le dessert aux voisins sur la terrasse",
        "meaning_en": "I'm serving dessert to the neighbors on the terrace.",
        "category_id": "builtin-cooking-food",
        "category_name": "Cooking & Food",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "mélanger",
        "frame_type": "a_object",
        "question": "Tu ____ le sucre ____ la crème encore tiède",
        "answer": "mélanges à",
        "full_answer": "Tu mélanges le sucre à la crème encore tiède",
        "meaning_en": "You're mixing the sugar into the still-warm cream.",
        "category_id": "builtin-cooking-food",
        "category_name": "Cooking & Food",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "goûter",
        "frame_type": "a_object",
        "question": "Je ____ ____ la sauce avant d'ajouter le sel",
        "answer": "goûte à",
        "full_answer": "Je goûte à la sauce avant d'ajouter le sel",
        "meaning_en": "I taste the sauce before adding the salt.",
        "category_id": "builtin-cooking-food",
        "category_name": "Cooking & Food",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "préparer",
        "frame_type": "a_object",
        "question": "Le chef ____ une assiette ____ enfants qui attendent",
        "answer": "prépare aux",
        "full_answer": "Le chef prépare une assiette aux enfants qui attendent",
        "meaning_en": "The chef is preparing a plate for the children who are waiting.",
        "category_id": "builtin-cooking-food",
        "category_name": "Cooking & Food",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "coudre",
        "frame_type": "a_object",
        "question": "Je ____ la poche ____ tablier avant le marché",
        "answer": "couds au",
        "full_answer": "Je couds la poche au tablier avant le marché",
        "meaning_en": "I'm sewing the pocket onto the apron before the market.",
        "category_id": "builtin-crafts-making",
        "category_name": "Crafts & Making",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "coller",
        "frame_type": "a_object",
        "question": "Je ____ la poignée ____ tiroir avec soin",
        "answer": "colle au",
        "full_answer": "Je colle la poignée au tiroir avec soin",
        "meaning_en": "I'm gluing the handle onto the drawer carefully.",
        "category_id": "builtin-crafts-making",
        "category_name": "Crafts & Making",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "ajuster",
        "frame_type": "a_object",
        "question": "J'____ la boucle ____ bracelet en cuir",
        "answer": "ajuste au",
        "full_answer": "J'ajuste la boucle au bracelet en cuir",
        "meaning_en": "I'm fitting the buckle to the leather bracelet.",
        "category_id": "builtin-crafts-making",
        "category_name": "Crafts & Making",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "présenter",
        "frame_type": "a_object",
        "question": "La prof ____ le roman ____ la classe dès neuf heures",
        "answer": "présente à",
        "full_answer": "La prof présente le roman à la classe dès neuf heures",
        "meaning_en": "The teacher presents the novel to the class at nine sharp.",
        "category_id": "builtin-education-learning",
        "category_name": "Education & Learning",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "J'____ ____ professeur pour signaler mon absence",
        "answer": "écris au",
        "full_answer": "J'écris au professeur pour signaler mon absence",
        "meaning_en": "I'm writing to the teacher to report my absence.",
        "category_id": "builtin-education-learning",
        "category_name": "Education & Learning",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "apprendre",
        "frame_type": "de_object",
        "question": "On ____ ____ ses brouillons en corrigeant ligne par ligne",
        "answer": "apprend de",
        "full_answer": "On apprend de ses brouillons en corrigeant ligne par ligne",
        "meaning_en": "You learn from your drafts by correcting them line by line.",
        "category_id": "builtin-education-learning",
        "category_name": "Education & Learning",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "expliquer",
        "frame_type": "a_object",
        "question": "Le tuteur ____ la méthode ____ nouveaux étudiants",
        "answer": "explique aux",
        "full_answer": "Le tuteur explique la méthode aux nouveaux étudiants",
        "meaning_en": "The tutor explains the method to the new students.",
        "category_id": "builtin-education-learning",
        "category_name": "Education & Learning",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "raconter",
        "frame_type": "a_object",
        "question": "Le guide ____ l'incendie ____ visiteurs dans la cour",
        "answer": "raconte aux",
        "full_answer": "Le guide raconte l'incendie aux visiteurs dans la cour",
        "meaning_en": "The guide tells the visitors about the fire in the courtyard.",
        "category_id": "builtin-history-culture",
        "category_name": "History & Culture",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "présenter",
        "frame_type": "a_object",
        "question": "Le musée ____ ses archives ____ public pendant l'été",
        "answer": "présente au",
        "full_answer": "Le musée présente ses archives au public pendant l'été",
        "meaning_en": "The museum presents its archives to the public during the summer.",
        "category_id": "builtin-history-culture",
        "category_name": "History & Culture",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "écrire",
        "frame_type": "a_object",
        "question": "L'historien ____ ____ maire pour protéger la plaque",
        "answer": "écrit au",
        "full_answer": "L'historien écrit au maire pour protéger la plaque",
        "meaning_en": "The historian writes to the mayor to protect the plaque.",
        "category_id": "builtin-history-culture",
        "category_name": "History & Culture",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "jouer",
        "frame_type": "de_object",
        "question": "Je ____ ____ piano sur trois morceaux ce soir",
        "answer": "joue du",
        "full_answer": "Je joue du piano sur trois morceaux ce soir",
        "meaning_en": "I'm playing piano on three songs tonight.",
        "category_id": "builtin-music",
        "category_name": "Music",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "assurer",
        "frame_type": "a_object",
        "question": "Le régisseur ____ ____ chanteur un retour plus net",
        "answer": "assure au",
        "full_answer": "Le régisseur assure au chanteur un retour plus net",
        "meaning_en": "The stage manager gives the singer a clearer monitor feed.",
        "category_id": "builtin-music",
        "category_name": "Music",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "accorder",
        "frame_type": "a_object",
        "question": "J'____ la guitare ____ l'oreille dans la loge",
        "answer": "accorde à",
        "full_answer": "J'accorde la guitare à l'oreille dans la loge",
        "meaning_en": "I'm tuning the guitar by ear in the dressing room.",
        "category_id": "builtin-music",
        "category_name": "Music",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "inviter",
        "frame_type": "a_object",
        "question": "On ____ le public ____ chanter pendant le refrain",
        "answer": "invite à",
        "full_answer": "On invite le public à chanter pendant le refrain",
        "meaning_en": "We're inviting the audience to sing during the chorus.",
        "category_id": "builtin-music",
        "category_name": "Music",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "trinquer",
        "frame_type": "a_object",
        "question": "Je ____ ____ votre victoire avant le dernier set",
        "answer": "trinque à",
        "full_answer": "Je trinque à votre victoire avant le dernier set",
        "meaning_en": "I'm toasting your win before the last set.",
        "category_id": "builtin-nightlife-partying",
        "category_name": "Nightlife & Partying",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "sortir",
        "frame_type": "a_object",
        "question": "On ____ ____ rooftop après le concert",
        "answer": "sort au",
        "full_answer": "On sort au rooftop après le concert",
        "meaning_en": "We're going out to the rooftop after the concert.",
        "category_id": "builtin-nightlife-partying",
        "category_name": "Nightlife & Partying",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "inviter",
        "frame_type": "a_object",
        "question": "J'____ les voisins ____ notre after au sous-sol",
        "answer": "invite à",
        "full_answer": "J'invite les voisins à notre after au sous-sol",
        "meaning_en": "I'm inviting the neighbors to our basement after-party.",
        "category_id": "builtin-nightlife-partying",
        "category_name": "Nightlife & Partying",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "présenter",
        "frame_type": "a_object",
        "question": "Je ____ le projet ____ la direction avant dix heures",
        "answer": "présente à",
        "full_answer": "Je présente le projet à la direction avant dix heures",
        "meaning_en": "I'm presenting the project to management before ten o'clock.",
        "category_id": "builtin-office-admin",
        "category_name": "Office & Admin",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "assurer",
        "frame_type": "a_object",
        "question": "Le manager ____ ____ client un appel de suivi lundi",
        "answer": "assure au",
        "full_answer": "Le manager assure au client un appel de suivi lundi",
        "meaning_en": "The manager guarantees the client a follow-up call on Monday.",
        "category_id": "builtin-office-admin",
        "category_name": "Office & Admin",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "transférer",
        "frame_type": "a_object",
        "question": "Nous ____ le dossier ____ service achats cet après-midi",
        "answer": "transférons au",
        "full_answer": "Nous transférons le dossier au service achats cet après-midi",
        "meaning_en": "We're transferring the file to purchasing this afternoon.",
        "category_id": "builtin-office-admin",
        "category_name": "Office & Admin",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "travailler",
        "frame_type": "a_object",
        "question": "Je ____ ____ budget du trimestre avant la réunion",
        "answer": "travaille au",
        "full_answer": "Je travaille au budget du trimestre avant la réunion",
        "meaning_en": "I'm working on the quarterly budget before the meeting.",
        "category_id": "builtin-office-admin",
        "category_name": "Office & Admin",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "grimper",
        "frame_type": "a_object",
        "question": "Nous ____ ____ refuge avant la pluie",
        "answer": "grimpons au",
        "full_answer": "Nous grimpons au refuge avant la pluie",
        "meaning_en": "We're climbing up to the refuge before the rain.",
        "category_id": "builtin-outdoors-nature",
        "category_name": "Outdoors & Nature",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "grimper",
        "frame_type": "a_object",
        "question": "Le chat ____ ____ mur pour suivre l'écureuil",
        "answer": "grimpe au",
        "full_answer": "Le chat grimpe au mur pour suivre l'écureuil",
        "meaning_en": "The cat climbs up the wall to follow the squirrel.",
        "category_id": "builtin-outdoors-nature",
        "category_name": "Outdoors & Nature",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "arriver",
        "frame_type": "a_object",
        "question": "On ____ ____ belvédère avant les autres",
        "answer": "arrive au",
        "full_answer": "On arrive au belvédère avant les autres",
        "meaning_en": "We arrive at the viewpoint before the others.",
        "category_id": "builtin-outdoors-nature",
        "category_name": "Outdoors & Nature",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "débattre",
        "frame_type": "de_object",
        "question": "Les députés ____ ____ la réforme jusqu'à minuit",
        "answer": "débattent de",
        "full_answer": "Les députés débattent de la réforme jusqu'à minuit",
        "meaning_en": "The MPs debate the reform until midnight.",
        "category_id": "builtin-politics-current-events",
        "category_name": "Politics & Current Events",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "imposer",
        "frame_type": "a_object",
        "question": "Le ministre ____ un nouveau barème ____ régions",
        "answer": "impose aux",
        "full_answer": "Le ministre impose un nouveau barème aux régions",
        "meaning_en": "The minister imposes a new scale on the regions.",
        "category_id": "builtin-politics-current-events",
        "category_name": "Politics & Current Events",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "accuser",
        "frame_type": "de_object",
        "question": "L'opposition ____ le préfet ____avoir bloqué le vote",
        "answer": "accuse d'",
        "full_answer": "L'opposition accuse le préfet d'avoir bloqué le vote",
        "meaning_en": "The opposition accuses the prefect of having blocked the vote.",
        "category_id": "builtin-politics-current-events",
        "category_name": "Politics & Current Events",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "promettre",
        "frame_type": "a_object",
        "question": "La candidate ____ une aide ____ villages isolés",
        "answer": "promet aux",
        "full_answer": "La candidate promet une aide aux villages isolés",
        "meaning_en": "The candidate promises aid to isolated villages.",
        "category_id": "builtin-politics-current-events",
        "category_name": "Politics & Current Events",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "mentir",
        "frame_type": "a_object",
        "question": "Il ____ ____ sœur depuis des mois",
        "answer": "ment à",
        "full_answer": "Il ment à sa sœur depuis des mois",
        "meaning_en": "He's been lying to his sister for months.",
        "category_id": "builtin-relationship-drama",
        "category_name": "Relationship Drama",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Je ____ ____ cette rupture à mes amis les plus proches",
        "answer": "parle de",
        "full_answer": "Je parle de cette rupture à mes amis les plus proches",
        "meaning_en": "I'm talking about this breakup to my closest friends.",
        "category_id": "builtin-relationship-drama",
        "category_name": "Relationship Drama",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "reprocher",
        "frame_type": "a_object",
        "question": "Elle ____ ____ Paul son ton devant tout le monde",
        "answer": "reproche à",
        "full_answer": "Elle reproche à Paul son ton devant tout le monde",
        "meaning_en": "She reproaches Paul for his tone in front of everyone.",
        "category_id": "builtin-relationship-drama",
        "category_name": "Relationship Drama",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "jouer",
        "frame_type": "a_object",
        "question": "On ____ ____ handball dans le vieux gymnase",
        "answer": "joue au",
        "full_answer": "On joue au handball dans le vieux gymnase",
        "meaning_en": "We're playing handball in the old gym.",
        "category_id": "builtin-sports-fitness",
        "category_name": "Sports & Fitness",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "marquer",
        "frame_type": "de_object",
        "question": "L'ailier ____ ____ la tête au second poteau",
        "answer": "marque de",
        "full_answer": "L'ailier marque de la tête au second poteau",
        "meaning_en": "The winger scores with a header at the far post.",
        "category_id": "builtin-sports-fitness",
        "category_name": "Sports & Fitness",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "a_object",
        "question": "Le coach ____ ____ remplaçants pendant l'échauffement",
        "answer": "parle aux",
        "full_answer": "Le coach parle aux remplaçants pendant l'échauffement",
        "meaning_en": "The coach talks to the substitutes during the warm-up.",
        "category_id": "builtin-sports-fitness",
        "category_name": "Sports & Fitness",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "changer",
        "frame_type": "de_object",
        "question": "L'entraîneur ____ ____ gardien avant la prolongation",
        "answer": "change de",
        "full_answer": "L'entraîneur change de gardien avant la prolongation",
        "meaning_en": "The coach changes goalkeeper before extra time.",
        "category_id": "builtin-sports-fitness",
        "category_name": "Sports & Fitness",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "acheter",
        "frame_type": "a_object",
        "question": "J'____ un café ____ kiosque avant le train",
        "answer": "achète au",
        "full_answer": "J'achète un café au kiosque avant le train",
        "meaning_en": "I'm buying a coffee at the kiosk before the train.",
        "category_id": "builtin-super-everyday",
        "category_name": "Super Everyday",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "parler",
        "frame_type": "de_object",
        "question": "Nous ____ ____ départ pendant le petit-déjeuner",
        "answer": "parlons de",
        "full_answer": "Nous parlons du départ pendant le petit-déjeuner",
        "meaning_en": "We're talking about the departure during breakfast.",
        "category_id": "builtin-super-everyday",
        "category_name": "Super Everyday",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "demander",
        "frame_type": "a_object",
        "question": "Je ____ ____ voisin de garder mon sac deux minutes",
        "answer": "demande au",
        "full_answer": "Je demande au voisin de garder mon sac deux minutes",
        "meaning_en": "I ask the neighbor to watch my bag for two minutes.",
        "category_id": "builtin-super-everyday",
        "category_name": "Super Everyday",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "envoyer",
        "frame_type": "a_object",
        "question": "J'____ la photo ____ groupe familial ce soir",
        "answer": "envoie au",
        "full_answer": "J'envoie la photo au groupe familial ce soir",
        "meaning_en": "I'm sending the photo to the family group tonight.",
        "category_id": "builtin-super-everyday",
        "category_name": "Super Everyday",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "louer",
        "frame_type": "a_object",
        "question": "Nous ____ la chambre ____ randonneurs pendant le festival",
        "answer": "louons aux",
        "full_answer": "Nous louons la chambre aux randonneurs pendant le festival",
        "meaning_en": "We're renting the room to hikers during the festival.",
        "category_id": "builtin-travel-tourism",
        "category_name": "Travel & Tourism",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "partir",
        "frame_type": "de_object",
        "question": "Le car ____ ____ terminal avant l'aube",
        "answer": "part du",
        "full_answer": "Le car part du terminal avant l'aube",
        "meaning_en": "The coach leaves from the terminal before dawn.",
        "category_id": "builtin-travel-tourism",
        "category_name": "Travel & Tourism",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "ajuster",
        "frame_type": "a_object",
        "question": "J'____ le gabarit ____ panneau étroit pour la découpe",
        "answer": "ajuste au",
        "full_answer": "J'ajuste le gabarit au panneau étroit pour la découpe",
        "meaning_en": "I'm adjusting the jig to the narrow panel for the cut.",
        "category_id": "builtin-woodworking",
        "category_name": "Woodworking",
        "note": "manual_dense_expansion",
    },
    {
        "verb": "coller",
        "frame_type": "a_object",
        "question": "Je ____ la traverse ____ panneau avant le serrage",
        "answer": "colle au",
        "full_answer": "Je colle la traverse au panneau avant le serrage",
        "meaning_en": "I'm gluing the rail onto the panel before clamping.",
        "category_id": "builtin-woodworking",
        "category_name": "Woodworking",
        "note": "manual_dense_expansion",
    },
]


def load_rows(path: Path) -> list[dict]:
    return json.loads(path.read_text(encoding="utf-8"))


def rebuild_ids(rows: list[dict]) -> list[dict]:
    family_counter: dict[tuple[str, str], int] = defaultdict(int)
    rebuilt = []
    for row in rows:
        item = dict(row)
        key = (item["verb"], item["frame_type"])
        family_counter[key] += 1
        item["frame_id"] = f"{item['verb']}_{item['frame_type']}_{family_counter[key]:02d}"
        rebuilt.append(item)
    return rebuilt


def write_outputs(rows: list[dict]) -> None:
    OUT_JSON.write_text(json.dumps(rows, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    OUT_JS.write_text("window.verbFrames = " + json.dumps(rows, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")

    by_category = Counter(row.get("category_name") or "" for row in rows)
    by_source = Counter(row.get("source") or "" for row in rows)
    lines = [
        "# French 200 Deck",
        "",
        f"- Total frame cards: {len(rows)}",
        "",
        "## By Source",
        "",
    ]
    for source, count in sorted(by_source.items()):
        lines.append(f"- {source}: {count}")
    lines.extend([
        "",
        "## By Category",
        "",
    ])
    for category_name, count in sorted(by_category.items()):
        lines.append(f"- {category_name}: {count}")
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    base_rows = load_rows(BASE_JSON)
    extra_rows = []
    for row in MANUAL_EXTRA_ROWS[:50]:
        item = dict(row)
        item["type"] = "frame"
        item["tense"] = "present"
        item["source"] = "manual_dense_expansion"
        extra_rows.append(item)
    merged = rebuild_ids(base_rows + extra_rows)
    write_outputs(merged)
    print(f"Wrote {len(merged)} frame cards to {OUT_JSON}")


if __name__ == "__main__":
    main()
