import gzip
import base64
import argparse
from pathlib import Path

TEMPLATE = """// Autogenerated loader from {original_name}
(() => {{
  const compressedBase64 = "{data}";
  const decompressed = new TextDecoder().decode(pako.inflate(base64ToUint8Array(compressedBase64)));
  const script = document.createElement("script");
  script.textContent = decompressed;
  document.body.appendChild(script);
}})();
"""

def gzip_base64(js_path: Path) -> str:
    with open(js_path, "rb") as f:
        raw = f.read()
    compressed = gzip.compress(raw)
    return base64.b64encode(compressed).decode("utf-8")

def generate_loader(js_path: Path):
    output_path = js_path.with_name(js_path.stem + ".loader.js")
    b64 = gzip_base64(js_path)
    content = TEMPLATE.format(data=b64, original_name=js_path.name)
    output_path.write_text(content, encoding="utf-8")
    print(f"✅ {output_path.name} written")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Compress JS files into loader scripts.")
    parser.add_argument("files", nargs="+", type=Path, help="JS files to compress")
    args = parser.parse_args()

    for js_file in args.files:
        if js_file.is_file():
            generate_loader(js_file)
        else:
            print(f"⚠️ Skipped (not found): {js_file}")

# import gzip
# import base64
# import argparse
# from pathlib import Path

# TEMPLATE = """<script>
# const compressedBase64 = "{data}";
# const decompressed = new TextDecoder().decode(pako.inflate(base64ToUint8Array(compressedBase64)));
# const script = document.createElement("script");
# script.textContent = decompressed;
# document.body.appendChild(script);
# </script>
# """

# def gzip_base64(js_path: Path) -> str:
#     with open(js_path, "rb") as f:
#         raw = f.read()
#     compressed = gzip.compress(raw)
#     return base64.b64encode(compressed).decode("utf-8")

# if __name__ == "__main__":
#     parser = argparse.ArgumentParser(description="Compress a JS file into a script-injection block.")
#     parser.add_argument("input", type=Path, help="Path to input .js file")
#     parser.add_argument("output", type=Path, help="Path to output .html snippet")
#     args = parser.parse_args()

#     b64 = gzip_base64(args.input)
#     with open(args.output, "w", encoding="utf-8") as f:
#         f.write(TEMPLATE.format(data=b64))

#     print(f"✅ Compressed script written to {args.output}")


# # import os
# # import re
# # import gzip
# # import json
# # import base64
# # import shutil
# # import argparse
# # from pathlib import Path

# # MAX_LINES = 20

# # def base64_encode_gzip_json(obj):
# #     json_str = json.dumps(obj, ensure_ascii=False, separators=(',', ':'))
# #     compressed = gzip.compress(json_str.encode('utf-8'))
# #     return base64.b64encode(compressed).decode('utf-8')

# # def compress_large_js_literals(js_file_path):
# #     with open(js_file_path, 'r', encoding='utf-8') as file:
# #         lines = file.readlines()

# #     output_lines = []
# #     buffer = []
# #     in_literal = False
# #     brace_count = 0
# #     literal_type = None
# #     var_line = ""
# #     object_name = ""

# #     for line in lines:
# #         if not in_literal:
# #             match = re.match(r'(const\s+(\w+)\s*=)\s*([{\[])', line)
# #             if match:
# #                 var_line = match.group(1)
# #                 object_name = match.group(2)
# #                 opener = match.group(3)
# #                 literal_type = "object" if opener == '{' else "array"
# #                 in_literal = True
# #                 buffer = [opener + '\n']
# #                 brace_count = 1
# #             else:
# #                 output_lines.append(line)
# #         else:
# #             open_char = '{' if literal_type == "object" else '['
# #             close_char = '}' if literal_type == "object" else ']'
# #             brace_count += line.count(open_char) - line.count(close_char)
# #             buffer.append(line)
# #             if brace_count == 0:
# #                 if len(buffer) > MAX_LINES:
# #                     js_literal = ''.join(buffer)
# #                     try:
# #                         data_obj = eval(js_literal, {}, {})
# #                         b64 = base64_encode_gzip_json(data_obj)
# #                         compressed_snippet = (
# #                             var_line + f' JSON.parse(new TextDecoder().decode(pako.inflate(base64ToUint8Array("{b64}"))));\n'
# #                         )
# #                         output_lines.append(compressed_snippet)
# #                     except Exception as e:
# #                         raise ValueError(f"Compression failed for variable '{object_name}': {e}")
# #                 else:
# #                     output_lines.append(f"{var_line} {''.join(buffer)}")
# #                 in_literal = False
# #                 buffer = []
# #                 object_name = ""
# #                 literal_type = None

# #     return output_lines

# # if __name__ == "__main__":
# #     parser = argparse.ArgumentParser(description="Compress large JS object/array literals safely using JSON.")
# #     parser.add_argument("files", nargs="+", help="Input .js files")
# #     parser.add_argument("--replace", action="store_true", help="Replace original file after backing up to .original.js")
# #     args = parser.parse_args()

# #     for path in args.files:
# #         try:
# #             path = Path(path)
# #             print(f"Processing: {path}")
# #             compressed_lines = compress_large_js_literals(path)

# #             if args.replace:
# #                 backup_path = path.with_suffix(".original.js")
# #                 if backup_path.exists():
# #                     print(f"❌ Backup already exists: {backup_path}. Skipping replacement.")
# #                     continue

# #                 shutil.copy(path, backup_path)
# #                 with open(path, "w", encoding="utf-8") as f:
# #                     f.writelines(compressed_lines)
# #                 print(f"✅ Backed up to {backup_path}, replaced original.")
# #             else:
# #                 output_path = path.with_name(f"{path.stem}.compressed.js")
# #                 with open(output_path, "w", encoding="utf-8") as f:
# #                     f.writelines(compressed_lines)
# #                 print(f"✅ Compressed version saved to {output_path}")

# #         except Exception as e:
# #             print(f"❌ Error processing {path}: {e}")


