const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),path=require('path');const root=path.resolve(__dirname,'..');
const fr={window:{}};vm.createContext(fr);vm.runInContext(fs.readFileSync(path.join(__dirname,'js/referenceCards.js'),'utf8'),fr);
for(const [verb,tense,form,o,r,expected] of [['donner','present','je donne',0,0,'je le lui donne'],['envoyer','present',"j’envoie".replace('’','\''),1,3,'je la leur envoie'],['rendre','passeCompose',"j'ai rendu",2,2,'je les leur ai rendues'],['montrer','plusQueParfait',"j'avais montré",1,1,'je la lui avais montrée']])assert.equal(fr.window.referenceCards.doubleReference({verb:{infinitive:verb},pronoun:'je',tense,conjugated:form},o,r).conjugated,expected);
for(const lang of ['spanish','catalan']){const ctx={window:{verbUsages:[]}};vm.createContext(ctx);const repo=path.join(root,lang+'-verbs');vm.runInContext(fs.readFileSync(repo+'/js/verbs.full.js','utf8')+';globalThis.data={verbs,tenses}',ctx);vm.runInContext(fs.readFileSync(repo+'/js/exercisePractice.js','utf8'),ctx);const api=ctx.window.exercisePractice;const cases=lang==='spanish'?[['dar','yo','doy',0,0,'yo se lo doy'],['dar','yo','doy',1,3,'yo se la doy'],['enviar','yo','envío',3,0,'yo se las envío']]:[['donar','jo','jo dono',0,0,"jo l'hi dono"],['donar','jo','jo dono',1,1,'jo la hi dono'],['donar','jo','jo dono',2,2,'jo els els dono'],['enviar','jo','jo envio',1,3,"jo els l'envio"]];for(const [v,p,f,o,r,a]of cases)assert.equal(api.doubleReference({verb:{infinitive:v},pronoun:p,tense:'present',conjugated:f},o,r).conjugated,a);
let n=0;for(const v of api.doubleVerbs){assert(ctx.data.verbs.some(x=>x.infinitive===v));for(const [tense,table]of Object.entries(ctx.data.tenses)){if(tense==='imperative')continue;for(const [key,f]of Object.entries(table[v]||{})){if(!f||f==='—')continue;for(let o=0;o<4;o++)for(let r=0;r<4;r++){const c=api.doubleReference({verb:{infinitive:v},pronoun:key.split('/')[0],tense,conjugated:f},o,r);assert(c,`${lang} ${v} ${tense}`);assert.equal(c.references.length,2);assert(!c.conjugated.includes('undefined'));n++;}}}}assert.equal(api.doubleReference({verb:{infinitive:api.doubleVerbs[0]},tense:'imperative'}),null);console.log(lang,n,'double combinations PASS');}
console.log('French double-pronoun order and agreement PASS');

vm.runInContext(fs.readFileSync(path.join(__dirname,'js/verbs.full.generated.js'),'utf8')+';globalThis.data={verbs,tenses}',fr);
let count=0;for(const v of fr.window.referenceCards.doubleVerbs){assert(fr.data.verbs.some(x=>x.infinitive===v));for(const [tense,rows]of Object.entries(fr.data.tenses)){for(const [pronoun,conjugated]of Object.entries(rows[v]||{})){for(let o=0;o<3;o++)for(let r=0;r<4;r++){const c=fr.window.referenceCards.doubleReference({verb:{infinitive:v},tense,pronoun,conjugated},o,r);assert(c, v+' '+tense);assert(!c.conjugated.includes('undefined'));count++;}}}}console.log('French',count,'loaded double combinations PASS');
// Every supported construction supplies both a full and replaced sentence.
for(const [repo,file,globalName,total] of [['proj1','referenceCards.js','referenceCards',44],['spanish-verbs','exercisePractice.js','exercisePractice',44],['catalan-verbs','exercisePractice.js','exercisePractice',38]]) {
 const ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,repo,'js',file),'utf8'),ctx);
 const api=ctx.window[globalName];assert.equal(api.doubleVerbs.length,total);
 for(const verb of api.doubleVerbs) {const entries=api.doubleUsageEntries(verb);assert.equal(entries.length,2);assert.notEqual(entries[0].example_fr,entries[1].example_fr);for(const entry of entries)for(const key of ['pattern','meaning_en','example_fr','example_en'])assert(entry[key]?.trim());}
}
for(const [v,p,expected] of [['permettre','permis','permises'],['dire','dit','dites'],['écrire','écrit','écrites'],['offrir','offert','offertes'],['apprendre','appris','apprises']]) {
 assert.equal(fr.window.referenceCards.doubleReference({verb:{infinitive:v},pronoun:'nous',tense:'plusQueParfait',conjugated:'nous avions '+p},2,2).conjugated,'nous les leur avions '+expected);
}
console.log('PASS 126 constructions, 252 example sentences, irregular participle agreements');
